name: Sync Dev Branch

on:
  push:
    branches:
      - main
jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge main to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git -v
          git remote -v
          echo 1
          git fetch origin
          echo 2
          git branch -r
          echo 3
          git branch -vv
          echo 4
          git pull origin main
          echo 5
          git switch dev
          echo 6
          git pull origin dev
          echo 7
          git branch -vv
          echo 8
          git merge main
          echo 9
          git push origin dev
