name: Sync Dev Branch

on:
  push:
    branches:
      - main
jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge main to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git branch -r
          git branch -vv
          git remote -v
          git checkout dev
          git pull origin dev
          git merge origin/main
          git push origin dev
