name: Sync Dev Branch

on:
  push:
    branches:
      - main
jobs:
  sync-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # - name: Checkout main
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main
      #     fetch-depth: 0

      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Merge main into dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 1
          git fetch origin
          echo 2
          git merge origin/main
          echo 3
          git push origin dev
