name: Sync Dev Branch

on:
  push:
    branches:
      - main
jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge main to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin dev:dev
          git checkout dev
          git merge origin/main
          git push origin dev
