name: Sync Dev Branch

on:
  push:
    branches:
      - main
jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Merge main to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git branch -vv
          git merge origin/main
          git push origin dev
